FEATURE_SCHEMAS: dict[str, dict[str, list[str]]] = {
    "fraud_risk": {
        "numeric": [
            "completed_trips_30d",
            "cancellation_rate_7d",
            "failed_payments_24h",
            "gps_spoofing_signals_24h",
            "route_deviation_ratio",
            "repeated_short_trip_ratio",
            "promo_abuse_count_30d",
            "device_account_count_30d",
            "average_trip_distance_km",
            "account_age_days",
            "current_hour_local",
        ],
        "categorical": ["city_code", "subject_type"],
        "target": "is_high_risk",
        "problem_type": "binary_classification",
        "threshold": 0.6,
    },
    "ride_cancellation_probability": {
        "numeric": [
            "estimated_fare",
            "estimated_eta_minutes",
            "surge_multiplier",
            "rider_cancellation_rate_30d",
            "driver_cancellation_rate_30d",
            "pickup_hour_local",
            "stop_count",
            "weather_severity_score",
            "demand_pressure_index",
        ],
        "categorical": ["ride_type", "city_code"],
        "target": "will_cancel",
        "problem_type": "binary_classification",
        "threshold": 0.5,
    },
    "driver_acceptance_probability": {
        "numeric": [
            "distance_to_pickup_km",
            "eta_to_pickup_minutes",
            "offered_fare",
            "surge_multiplier",
            "driver_acceptance_rate_30d",
            "driver_cancellation_rate_30d",
            "idle_time_minutes",
            "active_hours_today",
            "pickup_hour_local",
            "demand_pressure_index",
        ],
        "categorical": ["ride_type", "vehicle_type", "city_code"],
        "target": "will_accept",
        "problem_type": "binary_classification",
        "threshold": 0.55,
    },
    "demand_hotspot_prediction": {
        "numeric": [
            "hour_of_day",
            "day_of_week",
            "active_drivers",
            "ride_requests_last_15m",
            "avg_eta_minutes",
            "surge_multiplier",
            "weather_severity_score",
            "event_intensity_score",
        ],
        "categorical": ["zone_id", "city_code"],
        "target": "is_hotspot",
        "problem_type": "binary_classification",
        "threshold": 0.55,
    },
    "pooled_ride_compatibility": {
        "numeric": [
            "rider_a_wait_minutes",
            "rider_b_wait_minutes",
            "merged_trip_distance_km",
            "merged_trip_duration_minutes",
            "detour_minutes_rider_a",
            "detour_minutes_rider_b",
            "detour_ratio_rider_a",
            "detour_ratio_rider_b",
            "overlap_distance_ratio",
            "seat_utilization_ratio",
            "rider_rating_gap",
            "compatibility_rule_score",
        ],
        "categorical": ["city_code"],
        "target": "is_compatible",
        "problem_type": "binary_classification",
        "threshold": 0.58,
    },
}
